### ISSUE TITLE
NDcPP 3.0 - FAU_GEN.1.2 - removal of 'if applicable' caveat for Subject Identity

### ISSUE THREAD

**Issue by lachlan-turner** [ND-iTC/Documents#101]
**Provide the location of the issue**
FAU_GEN.1.2 - removal of 'if applicable' caveat for Subject Identity

**What is the correction request for the cPP? Please describe.**
Keep the if applicable caveat in place (undo the change)

**Describe the solution you'd like**
Keep the if applicable caveat in place.

**Describe alternatives you've considered**
Add an application note to clarify Subject Identity in the context of the requirement.

**Additional context**
Subject Identity is typically equated with User Identity (hence the caveat, as not all events involve users), however, a subject does not necessarily have to be a user. This should be ok as most audit logs contain some form of indication as to the ‘initiator’ of an event (e.g. system event). It might cause problems with overzealous evaluators / certifiers asking to see an explicit subject identity in every audit event.

**Comment by Kirky-J** [comment]
Feedback from NIAP advised us that we should clearly show where we have modified a CC Part 2 SFR, hence the inclusion of the original text with the strikethrough. You'll note that v3.0 hasn't changed the SFR from previous versions of the cPP, all of which simply omit the '(if applicable)' wording.
