### ISSUE TITLE
[cPP TYPO] Various Typos and Formatting Issues

### ISSUE THREAD

**Issue by kenji-lightship** [ND-iTC/Documents#102]
**Provide the location of the issue**
1.	Section 6.3.1.1, FAU_GEN.1.1, item c), bullet 4: “[list of other privileges]” should not have square brackets.
2.	Section 6.3.1.1, Application Note 3: Should “unanimous” be “unambiguous”?
3.	Section 6.6.3.1, Application Note 22, paragraph 3 (“Ability to update the TOE”): There are two close parentheses where there should only be one.
4.	Section 6.6.4.1: FMT_SMR.2.2 and FMT_SMR.2.3 requirements should not be bold.
5.	Section B.3.1.1, Application Note 63, first paragraph and Section B.3.1.5, Application Note 97, first paragraph: contain “_the reference identifier…” It’s not clear if the _ should be deleted or if the end formatting mark was accidentally omitted.
6.	Section B.3.1.1, Application Note 64, second paragraph: “…prevent the TOE to provide…” should be “…prevent the TOE from providing…”
7.	Section B.3.1.1, FCS_DTLSC_EXT.1.7: “_shall” It’s not clear if the _ should be deleted or if the end formatting mark was accidentally omitted.
8.	Section B.3.1.3, FCS_IPSEC_EXT.1.7: The IKEv2 indention and formatting is off. This should be formatted like FCS_IPSEC_EXT.1.8.
9.	Application Note 62 and 70: “depreciates” should be “deprecates”
10.	Section B.4.1, second paragraph: contains “..”
11.	Section B.5.2.1: FPT_TUD_EXT.2.2 requirement should not be bold.

**Comment by Kirky-J** [comment]
Fixes applied in editorial-v3_0-typos. Details on each highlighted below.

Section 6.3.1.1, FAU_GEN.1.1, item c), bullet 4: “[list of other privileges]” should not have square brackets. - _Extra brackets removed._
Section 6.3.1.1, Application Note 3: Should “unanimous” be “unambiguous”? - _Incorrect wording fixed._
Section 6.6.3.1, Application Note 22, paragraph 3 (“Ability to update the TOE”): There are two close parentheses where there should only be one. - _Fixed._
Section 6.6.4.1: FMT_SMR.2.2 and FMT_SMR.2.3 requirements should not be bold. - _Fixed._
Section B.3.1.1, Application Note 63, first paragraph and Section B.3.1.5, Application Note 97, first paragraph: contain “_the reference identifier…” It’s not clear if the _ should be deleted or if the end formatting mark was accidentally omitted. - _Extra formatting mark is erroneous and has been removed._
Section B.3.1.1, Application Note 64, second paragraph: “…prevent the TOE to provide…” should be “…prevent the TOE from providing…” - _Fixed._
Section B.3.1.1, FCS_DTLSC_EXT.1.7: “_shall” It’s not clear if the _ should be deleted or if the end formatting mark was accidentally omitted. - _I believe the underscore was erroneous and so has been removed._
Section B.3.1.3, FCS_IPSEC_EXT.1.7: The IKEv2 indention and formatting is off. This should be formatted like FCS_IPSEC_EXT.1.8. - _Appears to be another PDF rendering issue. ASCIIDOC version shows 1.7 and 1.8 using the same formatting_
Application Note 62 and 70: “depreciates” should be “deprecates” - _All instances of 'depreciates' have been replaced_
Section B.4.1, second paragraph: contains “..” - _Fixed_
Section B.5.2.1: FPT_TUD_EXT.2.2 requirement should not be bold. - _PDF rendering issue. ASCIIDOC version is not bold_
