### ISSUE TITLE
[cPP Correction] FAU_STG_EXT.1.3/LocSpace Other Actions

### ISSUE THREAD

**Issue by kenji-lightship** [ND-iTC/Documents#106]
**Provide the location of the issue**
cPP Section 6.3.2.2, FAU_STG_EXT.1.3/LocSpace
SD 

**What is the correction request for the cPP? Please describe.**
There should be an app note explaining appropriate/acceptable completion of the “other actions” assignment.

**Describe the solution you'd like**
Copy the Application Note from NDcPPv2.2e, "The ‘other action’ could in this case be defined as ‘send the new audit data to an external IT entity’." so there is some explanation.

**Comment by dundiddat** [comment]
Recommendation...

Create new application note under FAU_STG_EXT.1.3/LocSpace: "The ST author may use the "other action" assignment to describe other behavior such as log file rotation."

**Comment by KSinitski** [comment]
I recommend putting some limitations on "other action" so we don't see "_The TSF shall [start losing audit data] when the local storage space for audit data is full._" claims.

**Comment by dundiddat** [comment]
Recommending this rewording to address the comment from @KSinitski :

"The ST author may use the "other action" assignment to describe other **measurable** behavior **(e.g. frequency of** log file rotation **based on size and/or age of log files**)."
