### ISSUE TITLE
[cPP Correction] Incomplete SSH authentication algorithm specification

### ISSUE THREAD

**Issue by kenji-lightship** [ND-iTC/Documents#107]
**Provide the location of the issue**
Section 6.4.1.1, Application Note 9
Section B.4.1.2, Application Note 112
Possibly others

**What is the correction request for the cPP? Please describe.**
The cPP explicitly lists SSH host/public key algorithms; however, as of the SSH_PKG_v1.0, the list is out dated (and likely to be difficult to keep in sync). The SSH_PKG_v1.0 includes rsa-sha2-256 and rsa-sha2-512, which do not use X.509 certificates.

**Describe the solution you'd like**
Change these to something more generic like (based on Application Note 9): “When key generation is used for device authentication, other than non-X.509 SSH authentication algorithm, the public key is expected to be associated with an X.509v3 certificate.

**Comment by dundiddat** [comment]
Recommendations...

In application note 9… 
Change from: "When key generation is used for device authentication, other than **ssh-rsa (RFC 4253), ecdsa-sha2-nistp256 (RFC 5656), ecdsa-sha2-nistp384 (RFC 5656) and ecdsa-sha2-nistp521 (RFC 5656)**, the public key is expected to be associated with an X.509v3 certificate."
Change to: "When key generation is used for device authentication, other than **non-X.509 SSH authentication algorithm**, the public key is expected to be associated with an X.509v3 certificate."

In application note 112...
Change from: "The ST author must include FIA_X509_EXT.2 in all instances except when only SSH is selected **within FTP_ITC.1 or FPT_ITT.1 and ssh-rsa, ecdsa-sha2-nistp256, ecdsa-sha2-nistp384, and/or ecdsa-sha2-nistp521 authentication is also selected**. Additionally, FIA_X509_EXT.2 must also be included if FPT_TUD_EXT.2 is included in the ST."
Change to: "The ST author must include FIA_X509_EXT.2 in all instances except when only SSH is selected **(e.g. within FTP_ITC.1, FPT_ITT.1, or FTP_TRP.1/Admin) and only non-X.509 SSH authentication algorithms are used for SSH**. Additionally, FIA_X509_EXT.2 must also be included if FPT_TUD_EXT.2 is included in the ST."

**Comment by kenji-lightship** [comment]
Either recommendation addresses the issue. 

I have a slight preference for @KSinitski's suggestion. I think it makes the PP cleaner if we remove things that we can't define a clear reason for including.

@dundiddat's recommendation is safer. I don't think there is a reason SSH and X.509 need to be mentioned in this Application Note, but it appears this text has been in the PP for a while.

**Comment by a-kandiah** [comment]
I accept @dundiddat's suggestion for Application Notes 9 and 112. It's safer than removing the SSH and X.509 references in Note 9.
