### ISSUE TITLE
[cPP Correction] FCS_CKM.2 Ambiguous Algorithm Specification

### ISSUE THREAD

**Issue by kenji-lightship** [ND-iTC/Documents#108]
**Provide the location of the issue**
Section 6.4.1.2, FCS_CKM.2.1, 3rd bullet

**What is the correction request for the cPP? Please describe.**
“Finite field-based key establishment schemes that meet the following; NIST Special Publication 800-56A Revision 3, “Recommendation for Pair-Wise Key Establishment Schemes Using Discrete Logarithm Cryptography”” covers all FFC key establishment.

**Describe the solution you'd like**
To differentiate this from safe-prime methods and mirror SP 800-56A language, this should be updated to, "FFC Schemes using “FIPS 186-Type” parameter-size sets that meet the following: “Recommendation for Pair-Wise Key Establishment Schemes Using Discrete Logarithm Cryptography”"

**Additional context**
“FIPS 186-Type” is used in SP 800-56Ar3 Section 5.6.1.1.2.

**Comment by dundiddat** [comment]
Recommendation...
Accept Kenji's recommendation as stated in the issue description.

**Comment by KSinitski** [comment]
Consider adopting NIAP recent changes. See here for details: https://www.niap-ccevs.org/Documents_and_Guidance/view_td.cfm?TD=0717

**Comment by kenji-lightship** [comment]
The NIAP TD does not change or clarify FCS_CKM.2. It's not clear how the NIAP TD (FCS_CKM.1.1/AK) differs in a meaningful way from NDcPP v3.0 FCS_CKM.1.1 other than formatting.

**Comment by dundiddat** [comment]
Question, which is the more correct way to change this bullet?

As originally suggested...
_* FFC Schemes using “FIPS 186-Type” parameter-size sets that meet the following: “Recommendation for Pair-Wise Key Establishment Schemes Using Discrete Logarithm Cryptography”;_

Or with explicit reference to 800-56A...
_* FFC Schemes using “FIPS 186-Type” parameter-size sets that meet the following: **NIST Special Publication 800-56A Revision 3,** “Recommendation for Pair-Wise Key Establishment Schemes Using Discrete Logarithm Cryptography”;_

**Also, are there any assurance activities that need to be changed too?**
