### ISSUE TITLE
[cPP Correction] (D)TLS Server Specifies Client Requirements

### ISSUE THREAD

**Issue by kenji-lightship** [ND-iTC/Documents#113]
**Provide the location of the issue**
Section A.7.1.1, Application Note 47
Section A.7.1.2, Application Note 53

**What is the correction request for the cPP? Please describe.**
The Server SFR specifies client requirements, “This requirement adds that the client must be capable of presenting a certificate to a (D)TLS server for (D)TLS mutual authentication.”

**Describe the solution you'd like**
Recommend reverting this to NDcPPv2.2e text, "This requirement adds that the TSF must include support for client-side certificates for (D)TLS mutual authentication."

**Comment by plughy2** [comment]
Another alternative is "This requirement adds that the TSF must include support for (D)TLS mutual authentication."

**Comment by ianhallbc** [comment]
I tend to favor less words, but good with either update from Kenji or Rick here.

**Comment by kr15tyk** [comment]
Agreed to go with Ricks wording on today's TLSWG call.
