### ISSUE TITLE
[cPP Correction] (D)TLS (Dis)Allowed Cipher Suite

### ISSUE THREAD

**Issue by kenji-lightship** [ND-iTC/Documents#114]
**Provide the location of the issue**
FCS_DTLSC_EXT.1.1, Application Note 62
FCS_DTLSS_EXT.1.1, Application Note 70
FCS_TLSC_EXT.1.1 Application Note 96
FCS_TLSS_EXT.1.1, Application Note 104

**What is the correction request for the cPP? Please describe.**
These application notes say TLS_RSA_WITH_AES_128_CBC_SHA is not allowed even though it is included in List 1.

**Describe the solution you'd like**
This should be reverted to something like NDcPPv2.2e text:
There is no requirement to implement ciphersuites the RFCs specify as mandatory in order to claim conformance to this cPP.

**Additional context**
The NDcPPv2.2e text only accounted for RFC 5246, but TLS1.3 add an additional mandatory cipher suite.

**Comment by plughy2** [comment]
Agree an update is needed.  I believe the cPP intended to say "Support for TLS_RSA_WITH_AES_128_CBC_SHA is not needed in order to claim conformance to this cPP."

**Comment by ianhallbc** [comment]
Agree an update is needed to ensure there is no (especially this one) mandatory cipher suite for exact conformance required. Rick's suggestion looks good.

**Comment by kr15tyk** [comment]
Agreed to go with Kenji's wording on today's TLSWG call, "There is no requirement to implement ciphersuites the RFCs specify as mandatory in order to claim conformance to this cPP."
