### ISSUE TITLE
[cPP Correction] Uses of X.509

### ISSUE THREAD

**Issue by kenji-lightship** [ND-iTC/Documents#115]
**Provide the location of the issue**
Section B.4.1, paragraph 2

**What is the correction request for the cPP? Please describe.**
SSH is not listed as a protocol where X.509 SFRs could be included for.

**Describe the solution you'd like**
change “i.e.” to “e.g.” so the list of SFRs is only an example instead of a specification.

**Additional context**
Since it is extremely rare for SSH to claim X.509, it's not worth adding putting a lot of effort into this fix.

**Comment by dundiddat** [comment]
As recommended by Kenji in the issue description, change "i.e." to "e.g.".  

Also, could add to the list of SFRs in those same parentheses, "… or any x509v3 authentication mechanism in any SSH SFR.)"

**Comment by KSinitski** [comment]
My understanding that OpenSSH (i.e., vast majority of implementations) with X.509 does not fully implement PKI, where chains simply added to the local DB and trusted when encountered. This means imposing FIA_X509  dependencies would likely prevent claiming this SF.

**Comment by kenji-lightship** [comment]
The cPP already disallows that scenario, saying, "...FIA_X509_EXT.1/Rev and FIA_X509_EXT.2 is always required when using X.509 certificate-based authentication..." and RFC 6187 (referenced in the SSH FP) specifies validating chains.

**Comment by a-kandiah** [comment]
I agree with @kenji-lightship's comment about changing from i.e. to e.g. for the examples in paragraph 2.
