### ISSUE TITLE
[SD Correction] Reviewing Audit Logs

### ISSUE THREAD

**Issue by kenji-lightship** [ND-iTC/Documents#117]
**Provide the location of the issue**
Section 2.1.4.3, Test 5

**What is the correction request for the cPP? Please describe.**
This test requires viewing audit logs on the TOE; however, there are no requirements that the TOE provide an interface to review local audit records.

**Describe the solution you'd like**
Remove this test.

**Comment by kenji-lightship** [comment]
Are there any concerns or objections to removing Section 2.1.4.3 FAU_STG_EXT.1/LocSpace Test 5? If there aren't any objections, this is a simple update.

**Comment by dundiddat** [comment]
Recommendation...
As recommended by Kenji in the issue description, remove FAU_STG_EXT.1/LocSpace Test 5.

**Comment by KSinitski** [comment]
Objection. If the TOE implements local audit, there must be an interface to access (review, manually upload, etc.,) the local audit trail. Otherwise what is the point of having it?

**Comment by kenji-lightship** [comment]
(strangely) local review of audit logs has never been required, so this seems like a feature request. At one point a TD confirmed that there just needed to be enough functionality to verify log rotation (which many times seeing log file status (e.g., filenames, sizes, last updated)).

**Comment by a-kandiah** [comment]
I agree with @kenji-lightship. We should remove Test 5.

**Comment by KSinitski** [comment]
I disagree, we should not remove Test 5.

**Comment by dundiddat** [comment]
@KSinitski, instead of removing Test 5 would it be acceptable to modify the second sentence of Test 5?
Change from:  "During interruption, the evaluator shall perform a TSF-mediated action and verify the event is recorded in the audit trail."
Change to: During interruption, the evaluator shall perform a TSF-mediated action and, **if the TOE provides a mechanism to view locally stored audit records,** verify the event is recorded in the **local** audit trail.

**Comment by KSinitski** [comment]
The SFR does not specify local audit storage in sufficient detail and potentially makes it very misleading. In some cases (e.g., buffer) your proposal is reasonable, in other cases (e.g., log file) it is not. I recommend creating a new FAU_STG_EXT.1/LocSpace element that clarifies how the TOE implements this SF and tying Test 5 to that.

For example:

FAU_STG_EXT.1.x/LocSpace The TOE provided the following mechanisms to directly access locally stored audit records [selection: none, manual export, ability to view locally].

Test 5 [Conditional] In case manual export or ability to view locally is selected, during interruption the evaluator shall perform a TSF-mediated action and verify the event is recorded in the audit trail."

**Comment by kr15tyk** [comment]
Reopening pending resolution to comments.

**Comment by dundiddat** [comment]
> 

@KSinitski, the idea of allowing a selection of [selection: none, manual export] in a new FAU_STG_EXT.1.x/LocSpace sounds interesting, but I think that can be covered in TSS detail.  If we include a selection for "ability to view locally" then it seems like that should be tied to a selection-based SFR, such as FAU_SAR.1.   Perhaps we can do that in the next PP update after 3.0?
