### ISSUE TITLE
[SD Correction] Testing SP 800-56A

### ISSUE THREAD

**Issue by kenji-lightship** [ND-iTC/Documents#118]
**Provide the location of the issue**
FCS_CKM.2, Section 2.2.2.3, SP800-56A Key Establishment Schemes

**What is the correction request for the cPP? Please describe.**
For clarity it should specify that these tests are only for ECC and FIPS 186-type, now that safe-prime is also covered by 56A.

**Comment by kr15tyk** [comment]
@kenji-lightship Does editing the first sentence address this concern?

"The evaluator shall verify a TOE’s implementation of SP800-56A key agreement schemes using the following Function and Validity tests **for ECC and FIPS 186-type**."


SP800-56A Key Establishment Schemes

71.     The evaluator shall verify a TOE’s implementation of SP800-56A key agreement schemes using the following Function and Validity tests **for ECC and FIPS 186-type**. These validation tests for each key agreement scheme verify that a TOE has implemented the components of the key agreement scheme according to the specifications in the Recommendation. These components include the calculation of the DLC primitives (the shared secret value Z) and the calculation of the derived keying material (DKM) via the Key Derivation Function (KDF). If key confirmation is supported, the evaluator shall also verify that the components of key confirmation have been implemented correctly, using the test procedures described below. This includes the parsing of the DKM, the generation of MACdata and the calculation of MACtag.

**Comment by kenji-lightship** [comment]
I think the sub-heading should be updated. It should be updated in a way that is consistent with #108. Something like changing "SP800-56A Key Establishment Schemes" to "ECC and FIPS 186-type FFC SP800-56A Key Establishment Schemes". Kristy's suggested edit would also be helpful.

The reason for ensuring the subheading is updated is that it should be clear at the top level that the tests do not apply to safe-prime schemes even though the safe-prime selection includes "NIST Special Publication 800-56A Revision 3"
