### ISSUE TITLE
[SD Correction] Testing of EC X.509 Cert Chains

### ISSUE THREAD

**Issue by kenji-lightship** [ND-iTC/Documents#119]
**Provide the location of the issue**
Section 3.2.1.3, Paragraph 244
Section 4.3.1.3, Paragraph 562

**What is the correction request for the cPP? Please describe.**
The tests specified by TD527 have not been integrated (Test 8 is missing from /ITT and Test 8c is missing from /Rev).

**Describe the solution you'd like**
Update the SD with TD527.

**Additional context**
The reference to FCS_COP.1/SigGen to determine applicability is not correct. A TOE could have ECDSA in FCS_COP.1/SigGen for SSH or FTP_ITT while only using RSA for ITC communications.

**Comment by Kirky-J** [comment]
@kenji-lightship I've had a quick look at TD527 and the current SD and from what I can see, the whole of Test 8 in Para. 562 (/Rev) has not been updated - i.e. it's not just Test 8c which is missing. As you say, Test 8 is missing entirely from /ITT. 

Can you advise if the text from the TD simply needs to be added in full to /ITT and replace the existing (old?) text in /Rev?

**Comment by Kirky-J** [comment]
Text from TD527 has been properly transposed in to the SD. Fixed in editorial-SD-080223
