### ISSUE TITLE
[SD Correction] Negative (D)TLS Signature Algorithm Testing

### ISSUE THREAD

**Issue by kenji-lightship** [ND-iTC/Documents#120]
**Provide the location of the issue**
Paragraphs 300, 301, 331, 332, 388, and 529 (most (D)TLS Signature Algorithm tests)

**What is the correction request for the cPP? Please describe.**
The remarks do not make sense, expect in paragraph 301. Paragraph 301 is the only paragraph with an item c.

**Describe the solution you'd like**
Delete item c and all remarks in these paragraphs.

**Additional context**
The initial draft of the SignatureSchemes requirements included tests that would require a specially developed client. These tests were supposed to have been removed.

**Comment by kr15tyk** [comment]
Agreed, it makes sense to remove item c and the remarks.

**Comment by kr15tyk** [comment]
On the TLSWG  call today, the team agreed with these changes.

**Comment by kr15tyk** [comment]
Changes merged in PR#130.
