### ISSUE TITLE
[cPP Correction] Functional Package for SSH audit requirements

### ISSUE THREAD

**Issue by ConanHoye** [ND-iTC/Documents#123]
Section 2.2 / Application note 58.

There are ambiguous audit requirements when using the Functional Package for Secure Shell (SSH).  The FP_SSH allows for the selection of "none" in the audit events.  The MINT has discussed this and said the audit requirements from FTP_ITC.1, FPT_TRP.1/Admin or FTP_ITT.1 set the level of the requirement, but this is not explicit in the text.

Request: Update applcation note 58 to include a statement of the level of auditing required when using the SSH functional package.

Possible update text could read:  "SSH is not a required component of this cPP. If a TOE implements SSH and the ST author selects SSH in FTP_ITC.1.1, FTP_TRP.1.1/Admin, or FPT_ITT.1.1, the ST should include the Functional Package for Secure Shell (SSH) as referenced in section 2.2.  Additionally when the Functional Package for Secure Shell is used the audit requirements for FTP_ITC.1.1, FTP_TRP.1.1/Admin, or FPT_ITT.1.1 apply to each claimed interface."

An alternative is to update Section 2.2 with this information.

**Comment by dundiddat** [comment]
Recommendation...

In PP: Add to the last paragraph of application note 58 (in section B.1),  "Additionally, when the Functional Package for Secure Shell is used the audit requirements for FTP_ITC.1.1, **FTP_TRP.1.1/Admin,** or FPT_ITT.1.1 apply to each claimed interface."

**Comment by KSinitski** [comment]
This needs to say 'SHALL apply' or some will attempt to argue that the audit is optional.

**Comment by dundiddat** [comment]
Agreeing with @KSinitski, so the additional sentence would be: 
"Additionally, when the Functional Package for Secure Shell is used the audit requirements for FTP_ITC.1.1, **FTP_TRP.1.1/Admin,** or FPT_ITT.1.1 **shall** apply to each claimed interface."

**Comment by a-kandiah** [comment]
I agree with the original suggestion and subsequent changes suggested by @KSinitski and @dundiddat.
