### ISSUE TITLE
[cPP TYPO] 

### ISSUE THREAD

**Issue by Bill-yc** [ND-iTC/Documents#124]
**Provide the location of the issue**
Section C.1.2.4 FAU_STG_EXT.3

**Describe the typo that you've identified. Please be specific**
FAU_STG_EXT.3 is an extended component without any operations. However the text "generate a warning to inform the administrator" and "exceeds the local audit trail storage capacity" are italic, which seems not needed.

**Describe the solution you'd like**
Remove the italic of these two sentences.

**Additional context**
Add any other context or screenshots about the change request here.

**Comment by Kirky-J** [comment]
Italic formatting removed. Fixed in editorial-cPP-2001223
