### ISSUE TITLE
FCS_SSH_EXT.1.7 KDF and RFC 5656

### ISSUE THREAD

**Issue by Kirky-J** [ND-iTC/Documents#128]
**Location**
FCS_SSH_EXT.1.7

As per FCS_SSH_EXT.1.7, SSH KDF shall be compliant to RFC 4253 (Section 7.2) or RFC 5656 (Section 4). However, currently, ACVP testing for SSH KDF is for testing compliance to NIST SP800-135, as per Section 6 of https://pages.nist.gov/ACVP/draft-celi-acvp-kdf-ssh.html, and according to NIST SP800-135 (Section 5.2), SSH KDF is compliant to RFC 4253.
	 
Thus, what test shall be done if SSH KDF claims to be compliant to RFC 5656 (Section 4), or ECDH is used for SSH key exchange? Or, does it imply that we shall NOT claim ECDH for SSH key exchange currently?

**Comment by dundiddat** [comment]
This should be covered by the fix for issue #127.

**Comment by kenji-lightship** [comment]
This seems to be an SSH Functional package issue, not an NDcPP issue.

No tests are defined in the SSH Functional Package v1.0 for FCS_SSH_EXT.1, so I think the answer is "no tests" for either selection.

**Comment by dundiddat** [comment]
Closing this issue after discussion in MINT meeting on 2023-02-13.
