### ISSUE TITLE
Strikethrough Comments Remain

### ISSUE THREAD

**Issue by Kirky-J** [ND-iTC/Documents#133]
In Section 6.3.1, 6.4, 6.8. 6.9 there are strikethrough comments. These should be deleted (if appropriate). Need to check the remainder of the document for similar.

**Comment by kr15tyk** [comment]
Per NIAP, strikethrough may be required to show a refinement from CC2 wording. There were a number of formatting changes as requested by NIAP that were implemented into the draft in PR https://github.com/ND-iTC/Documents/pull/81.
