### ISSUE TITLE
Use of italics in FCS_DTLSS_EXT.2.4, FCS_DTLSS_EXT.2.1 and FCS_TLSS_EXT.1.6

### ISSUE THREAD

**Issue by Kirky-J** [ND-iTC/Documents#134]
FCS_DTLSS_EXT.2.4 - Selections should be in italics
FCS_DTLSS_EXT.2.1 - Selections should be in italics 
FCS_TLSS_EXT.1.6 - Italics shouldn't be used

**Comment by kr15tyk** [comment]
Fixed in TLSWG-v3-editorial-fixes branch.
