### ISSUE TITLE
Section 3.1.2. FAU_STG_EXT.2/LocSpace Counting lost audit data

### ISSUE THREAD

**Issue by Kirky-J** [ND-iTC/Documents#135]
SFR FAU_STG_EXT.2/LocSpace is referenced several times in the SD.  However SFR FAU_STG_EXT.2/LocSpace is no longer found in NDcPPv3.0. Correct if needed

**Comment by plughy2** [comment]
Suggestions:
Change all references of "FAU_STG_EXT.2/LocSpace" in the SD to "FAU_STG_EXT.2" 
Change all references of "FAU_STG_EXT.3/LocSpace" in the SD to "FAU_STG_EXT.3"

**Comment by dundiddat** [comment]
This should be covered by the fix for issue #155.
