### ISSUE TITLE
Section 6.6.4.1 FMT_SMR.2 Restrictions on security roles

### ISSUE THREAD

**Issue by Kirky-J** [ND-iTC/Documents#142]
Under “FMT_SMR.2.3 The TSF shall ensure that the conditions” What happen to "The Security Administrator role shall be able to administer the TOE locally" in addition to remotely? Is locally administer SFR no longer required?

**Comment by dundiddat** [comment]
Recommendation...
No change to PP/SD.  

Explanation: The requirement to be able to administer the TOE locally was removed as part of PR #47. https://github.com/ND-iTC/Documents/pull/47"

**Comment by kenji-lightship** [comment]
Agree, no change is needed.

**Comment by KSinitski** [comment]
Agreed

**Comment by dundiddat** [comment]
Closing this issue after discussion in MINT meeting on 2023-02-13.
