### ISSUE TITLE
Section 6.4.1.1 FCS_CKM.1 - Strikethroughs

### ISSUE THREAD

**Issue by Kirky-J** [ND-iTC/Documents#144]
Below the fourth bullet and some other places, “ and specified cryptographic key sizes [assignment: cryptographic key sizes] that meet the following: [assignment: list of standards].” Should all strike-through texts be removed?

**Comment by kr15tyk** [comment]
IMO, the answer is no, it should not be removed because it shows the refinement from CC2 wording.
