### ISSUE TITLE
FAU_STG_EXT.2/.3 labelling - LocSpace

### ISSUE THREAD

**Issue by Kirky-J** [ND-iTC/Documents#155]
Section A.2

There are SFRs labelled “FAU_STG_EXT.2” and “FAU_STG_EXT.3” in the PP but are labelled “FAU_STG_EXT.2/LocSpace” and “FAU_STG_EXT.3/LocSpace” in the SD

Ensure the names of the SFRs are consistent in the PP and SD

**Comment by plughy2** [comment]
Suggestions:
Change all references of "FAU_STG_EXT.2/LocSpace" in the SD to "FAU_STG_EXT.2"
Change all references of "FAU_STG_EXT.3/LocSpace" in the SD to "FAU_STG_EXT.3"

**Comment by kr15tyk** [comment]
I agree with Rick's comment. THe changes in the cPP were never carried over into the SD.

**Comment by dundiddat** [comment]
Recommend accepting the suggestions from plughy2:
Suggestions:
Change all references of "FAU_STG_EXT.2/LocSpace" in the SD to "FAU_STG_EXT.2"
Change all references of "FAU_STG_EXT.3/LocSpace" in the SD to "FAU_STG_EXT.3"

**Comment by KSinitski** [comment]
Agreed.
