### ISSUE TITLE
FIA_UAU.7 missing from App Note 18

### ISSUE THREAD

**Issue by Kirky-J** [ND-iTC/Documents#156]
Section 6.5.1.1, FIA_UIA_EXT.1.3, Application Note 18

2nd paragraph: The direction to include FIA_UAU.7 from Appendix B is missing; without it being specified here, there is no mechanism for the ST author to include it.

Add FIA_UAU.7 to the list of SFRs to be included from Appendix B

**Comment by dundiddat** [comment]
Recommendation...

Disregard and/or link to issue #162 .  The section number, SFR and application note referenced in the issue don't correlate to each other.  Regardless, the resolution of issue #162 should resolve this concern.

**Comment by dundiddat** [comment]
Closing this issue after discussion in MINT meeting on 2023-02-13.

This issue will be resolved when #162 is resolved.
