### ISSUE TITLE
FCS_DTLSS_EXT.2.4 signature_algorithms extension

### ISSUE THREAD

**Issue by Kirky-J** [ND-iTC/Documents#157]
Section A.7.1.1, FCS_DTLSS_EXT.2.4 also Section A.7.1.2, FCS_TLSS_EXT.2.4

Application Note 50 mentions that the Certificate Request message includes the algorithms in the signature_algorithms extension for DTLS 1.3; turns out that DTLS 1.2 also supports this extension.

Add “in the signature_algorithms extension” after “the following algorithms”

**Comment by kr15tyk** [comment]
In today's TLS working group call, the group agreed with Kenji's comments above. No changes required.
