### ISSUE TITLE
(D)TLS 1.3 support - Multiple Linked Issues

### ISSUE THREAD

**Issue by Kirky-J** [ND-iTC/Documents#160]
Section B.3.1.1, FCS_DTLSC_EXT.1.8
Section B.3.1.1, FCS_DTLSS_EXT.1.10
Section B.3.1.5, FCS_TLSC_EXT.1.8
Section B.3.1.5, FCS_TLSS_EXT.1.7

•	This requirement addresses (D)TLS 1.3 which the TOE may not support.
•	The 2 sentences of this requirement seem to specify 2 different requirements.

•	Might need to make this a separate selection-based SFR
•	Might need to break into 2 SFRs

**Comment by kenji-lightship** [comment]
The requirements only apply to (D)TLS1.3, but since they are specifying (D)TLS1.3 features the TOE shall not permit, I think it's simpler to say that TOEs that do not support (D)TLS1.3 implicitly meet the requirement. The TOE can't support a (D)TLS1.3 feature if it doesn't support (D)TLS1.3.

**Comment by kr15tyk** [comment]
In today's TLS working group call, the group agreed with Kenji's comments above. No changes required.
