### ISSUE TITLE
Lack of statement indicating when FIA_AFL, FIA_UAU, FIA_PMG_EXT should be used

### ISSUE THREAD

**Issue by Kirky-J** [ND-iTC/Documents#162]
Section B.4.2

There are no explicit statements in this section mandating when the following SFRs need to be included:
FIA_AFL, FIA_UAU, FIA_PMG_EXT

Add a statement stating when the SFRs should be included in the PP

**Comment by dundiddat** [comment]
Recommendation...

In PP: Add a sentence to opening paragraph of section B, "Any SFRs not listed in section B (e.g. FIA_AFL, FIA_UAU, FIA_PMG_EXT) are baseline (mandatory) requirements found in section 6 or optional requirements found in section A."

Also in PP: In the application note for FIA_AFL.1...
Change from:
"If the TOE offers the ability for **a remote Administrator account to be disabled in line with **FIA_AFL.1**** then the ST author must select the option “Ability to re-enable an Administrator account” to allow the account to be re-enabled by a local Administrator."
Change to: 
"If the TOE offers the ability for **_an administrator to unlock a locked account, relevant to with FIA_AFL.1.2,_** then the ST author must select the option “Ability to re-enable an Administrator account” to allow the account to be re-enabled by a local Administrator."

**Comment by kenji-lightship** [comment]
I don't think a generic addition to Section B is sufficient.

To be consistent with TLS and IPsec selection-based requirements, references to specific SFRs/selections should be in the intro (currently there are descriptions, but they are not that specific) to the SFR, family, or function:
- FIA_AFL (B.4.2)
- FIA_UAU (B.4.3)
- FIA_PMG_EXT (B.4.4)

For comparison, B.3.1.5 references FPT_ITT.1, FTP_ITC.1, or FTP_TRP.1/Admin when describing when TLS must be included.

I agree with @dundiddat's edit to the Application Note, but "a local Administrator" should also be changed to just "an Administrator."

**Comment by plughy2** [comment]
A statement regarding when to include FIA_AFL.1 and FIA_PMG_EXT.1 is in Application Note 18: 

 _If "Web GUI password" or "SSH password" is selected for remote authentication mechanism the ST author specifies an appropriate cryptographic protocol in FTP_TRP.1/Admin (e.g., "HTTPS" or "SSH") and includes FIA_AFL.1, FIA_PMG_EXT.1, FPT_APW_EXT.1 from Appendix B_.

For FIA_UAU.7, the statement in B.4.3 seems sufficiently clear.  For consistency, FIA_UAU.7 could be added to the fourth paragraph in Application Note 18 (addition in bold):

_If the optional selection of "Ability to administer the TOE locally" is specified in FMT_SMF.1 the ST author selects "password-based" local authentication mechanism and includes FIA_PMG_EXT.1, FPT_APW_EXT.1 **and FIA_UAU.7** from Appendix B. Alternatively, the ST author may complete the assignment operation to specify a local authentication mechanism that is non-password based._

**Comment by kenji-lightship** [comment]
This issue is not high-priority. The comment is specifically about Section B.4.2, not Application Note 18. When looking at the other selection based requirements in Section B, the PP is specific about which SFRs to consider. Section B.4.2 only has general statements, but they should be understandable by most readers.

Overall, I think the PP is clear enough. 

Agree with the FIA_UAU.7 addition to Application Note 18.

**Comment by tamcompton** [comment]
I don't think any change is needed. I feel like we are looking to add text and it's not clear we are making things more clear to the reader. I have never seen this as an issue so I think we should leave the text as is (with the exception of the addition to the app note 18)
