### ISSUE TITLE
Section A.7.1.2, FCS_TLSS_EXT.2.4, Application Note 56

### ISSUE THREAD

**Issue by kr15tyk** [ND-iTC/Documents#164]
Application Note 56. Many TLS v1.2 implementations, including OpenSSL, ignore signature_algorithm extension. Recommend consulting with a wider iTC prior to making this into a mandatory requirement.

**Comment by kr15tyk** [comment]
Discussed in today's TLS working group call. The consensus was that for TLS 1.2, RFC 5246, section-7.4.1.4.1, does not mandate that the server does anything with the extension; therefore, it's not a mandatory requirement for TLS 1.2.

**Comment by kenji-lightship** [comment]
No requirement to include the signature_algorihtms extension in TLS1.2 Certificate Request messages is specified by this SFR or Application Note. It is not clear what the issue being raised is.

Note: The TLS1.2 Certificate Request message (https://www.rfc-editor.org/rfc/rfc5246#section-7.4.4) does not support extensions.
