### ISSUE TITLE
Section B.3.1.5, FCS_TLSS_EXT.1.3 (and others) 

### ISSUE THREAD

**Issue by kr15tyk** [ND-iTC/Documents#169]
FCS_TLSS_EXT.1.3 (and others) includes “of size 2048 bits” and “ffdhe2048” selections. These selections are of different level of details that potentially overlap (i.e., ffdhe2048 is of size 2048 bits). Is the intent behind “of size 2048 bits” is to specify MODP (RFC 3526) groups? If so, why not do so directly?

**Comment by kenji-lightship** [comment]
The wording could be tightened up to differentiate ffdhe and other DHE key agreement.

The generic sizes are meant to be generic and not necessarily refer to RFC 3526 groups. Per FCS_CKM.2, a TOE can theoretically (even if unlikely) use FIPS 186-Type FFC Parameter-size Sets.

**Comment by kr15tyk** [comment]
TLSWG agrees there's some overlap and it's a little ambiguous, but clear enough with the app note explanation. This issue is on hold due to possible deprecation of ffdhe for TLS, https://mailarchive.ietf.org/arch/msg/tls/iZGV0kKHfbV5MrO-owB8mFwfffw/.

**Comment by kr15tyk** [comment]
This issue was resolved in NDcPPv3.0e.
