### ISSUE TITLE
Section 4.2.1.1 and 4.2.6.1, FCS_(D)TLSC_EXT.1.4, TSS correction

### ISSUE THREAD

**Issue by kr15tyk** [ND-iTC/Documents#175]
Section 4.2.1.1, FCS_DTLSC_EXT.1.4, TSS
Section 4.2.6.1, FCS_TLSC_EXT.1.4, TSS
Since the SFR has a selection for whether the Supported Groups Extension is presented, The TSS EA is missing a conditional.

Suggested change:
Add “If “present the Supported Groups Extension” is selected”

**Comment by plughy2** [comment]
Recommend updating as per the suggestion.

**Comment by kr15tyk** [comment]
Agreed to suggested change on today's TLSWG call.
