### ISSUE TITLE
Section 4.2.1.3 and 4.2.6.3, FCS_(D)TLSC_EXT.1.4, Tests

### ISSUE THREAD

**Issue by kr15tyk** [ND-iTC/Documents#176]
Section 4.2.1.3, FCS_DTLSC_EXT.1.4, Tests
Section 4.2.6.3, FCS_TLSC_EXT.1.4, Tests
Test 3 and 4: Selecting either secp groups or ffdhe curves requires that “present the Supported Groups Extension” is selected

Suggested change:
Add “ “present the Supported Groups Extension” is selected and ” after “If” at the beginning

**Comment by plughy2** [comment]
Suggest updating Test 3 to: 
if "present the Supported Groups Extension" is claimed with any selections of "secp256r1", "secp384r1", or "secp521r1",  the evaluator shall…

Suggest updating Test 4 to: 

if "present the Supported Groups Extension" is claimed with any selections of "ffdhe2048", "ffdhe3072", "ffdhe4096", "ffdhe6144", or "ffdhe8192", the evaluator shall...

**Comment by kr15tyk** [comment]
Agreed to no change on today's TLSWG call.
