### ISSUE TITLE
Inconsistent language in SD

### ISSUE THREAD

**Issue by kr15tyk** [ND-iTC/Documents#180]
There are 13 instances of “carry out” in the SD that could be changed to "perform".

Section 4.2.2.3, FCS_DTLSS_EXT.1.7, Tests
Section 4.2.7.3, FCS_TLSS_EXT.1.4, Tests
•	Tests 5 and 6: “The evaluator shall carry out” is not consistent with the language used throughout the SD
•	Tests 2-4: “The evaluator shall carry out” is not consistent with the language used throughout the SD

Suggested change:
Change “carry out” to “perform”

**Comment by Kirky-J** [comment]
Some instances of "carry out" changed to "perform". Some instances have remained where evaluator is guided to "carry out" a set of steps.

**Comment by kr15tyk** [comment]
Issues resolved with PR #209
