### ISSUE TITLE
Section 4.2.5.3, FCS_NTP_EXT.1.4 correction

### ISSUE THREAD

**Issue by kr15tyk** [ND-iTC/Documents#182]
Test 2:
•	“an otherwise valid but unsolicited NTP Server responses” is not grammatically correct
•	The test intent is repeated.

Suggested changes:
•	Change “responses” to “response”
•	Delete the next-to-last sentence which repeats the intent stated at the beginning.

**Comment by Kirky-J** [comment]
Typo correct and additional sentence removed.

**Comment by kr15tyk** [comment]
Issues resolved with PR #209
