### ISSUE TITLE
Section 4.2.5.3, FCS_NTP_EXT.1.4 Test 2 

### ISSUE THREAD

**Issue by kr15tyk** [ND-iTC/Documents#183]
As written, Test 2 appears to want the CCTL to create an “NTP Server Response” packet which is distinctly different from an NTP broadcast/multicast packet (i.e., it has authentication and keying material vice the broadcast packet which does not.
TOE response to broadcast packets is specifically covered in testing for FCS_NTP_EXT.1.3.  Test 2, as currently written, appears to allow the reuse of broadcast packets to demonstrate TOE functionality in this test.  
From a technical evaluation standpoint, it is difficult to know if the TOE rejected the packet because it was a broadcast/multicast packet or if it was because the NTP Server was not configured on the TOE.

Suggested change:
For FCS_NTP_EXT.1.4 Test 2 (Line 491), the intent of this test should be clarified to explicitly allow or disallow the use of broadcast or multicast packets to satisfy the test requirement.
•	If broadcast/multicast packets are part of the intent, additional testing should be considered to evaluate that the TOE is able to ignore unsolicited packets from rogue NTP servers.

**Comment by dundiddat** [comment]
Recommendation...

Add to test 2: "This test must use a unicast packet, not broadcast nor multicast. The source IP of the packet from the NTP server must not correspond to any configured NTP server on the TOE, but the packet must otherwise conform to at least one packet used to test FCS_NTP_EXT.1.2."

**Comment by KSinitski** [comment]
I don't think clarification of Test 2 is necessary, as FCS_NTP_EXT.1.3 element already prevents acceptance of broadcast and/or multicast packets in the evalauted configuration.

If further clarity is still required, I recommend updating Application Note 95 in the following way:

The TOE has to support configuration of at least 3 **unicast** time sources ...

**Comment by tamcompton** [comment]
Agreed test 2 needs no changes.  The test for FCS_NTP_ECT.1.3 states "The evaluator shall confirm the TOE is configured to not accept broadcast and multicast NTP packets that would result in the timestamp being updated" Seems like we specifically call those types of packets out already.

**Comment by dundiddat** [comment]
Agreed above and in MINT meeting on Feb 20 to not make any changes to the test nor to the application note.
