### ISSUE TITLE
SD section order does not align with cPP

### ISSUE THREAD

**Issue by kr15tyk** [ND-iTC/Documents#184]
Section 4.3.5 and 4.3.6
The ordering of the SFRs in the SD does not align with the ordering in the PP.

Suggested change: swap section 4.3.5 and 4.3.6 in the SD

Section 4.5
The ordering of the SFRs in the SD does not align with the ordering in the PP.

Suggested change: move FMT_MOF.1/Services before FMT_MOF.1/AutoUpdate to align with the ordering in the PP

**Comment by Kirky-J** [comment]
Swapped Sections 4.3.5 and 4.3.6. New order is: 

4.3.5 FIA_UAU.7 Protected Authentication Feedback
4.3.6 FIA_PMG_EXT.1 Password Management

Moved FMT_MOF.1/Services ahead of FMT_MOF.1/AutoUpdate.

**Comment by kr15tyk** [comment]
Issues resolved with PR #209
