### ISSUE TITLE
Section 4.2.2.1 para 395, FCS_DTLSS_EXT.1.4 TSS

### ISSUE THREAD

**Issue by kr15tyk** [ND-iTC/Documents#195]
FCS_DTLSS_EXT.1.4 TSS: “…the key exchange parameters of the server Key Exchange message.” Would the Server Key Exchange message be present in all circumstances?  

Suggested change:
As this is a documentation requirement, recommend rewording the requirement in a more generic way (i.e., without explicitly mentioning optional Server Key Exchange message).

**Comment by plughy2** [comment]
Suggest changing the TSS requirement to be consistent with FCS_TLSS_EXT.1.3.

“The evaluator shall verify that the TSS lists all EC Diffie-Hellman curves and/or Diffie-Hellman groups used in the key establishment by the TOE when acting as a DTLS Server. The evaluator shall ensure these algorithms are consistent with the selected ciphersuites.”

**Comment by kr15tyk** [comment]
Agreed to go with Rick's suggested wording on today's TLSWG call.

**Comment by ouarak** [comment]
the proposed wording does not talk about RSA key exchange. i suggest the below:

"The evaluator shall verify that the TSS describes the key exchange mechanisms used by the TOE during the DTLS handshake protocol. The evaluator shall ensure these algorithms are consistent with the selected ciphersuites

**Comment by plughy2** [comment]
@ouarak There isn't a Server Key Exchange Message sent in the handshake when using RSA key establishment.

**Comment by ouarak** [comment]
I agree, but the requirement is to talk about key exchange algorithm, in general, that happen during a TLS handshake.

Fathi

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by plughy2** [comment]
Since there isn't a key exchange message, it wouldn't add value to require ST author to describe in the TSS what you're looking for.  Similar to DH and ECDH, we don't ask to describe how Diffie-Hellman calculates P and G or how points on a NIST curves are calculated. That's best up to cryptographic algorithm validations.  This is consistent with all earlier versions of the NDcPP.

**Comment by kr15tyk** [comment]
On today's call, the TLSWG agreed to Rick's suggested wording.

“The evaluator shall verify that the TSS lists all EC Diffie-Hellman curves and/or Diffie-Hellman groups used in the key establishment by the TOE when acting as a DTLS Server. The evaluator shall ensure these algorithms are consistent with the selected ciphersuites.”
