### ISSUE TITLE
Removal of text relating to fail verdict

### ISSUE THREAD

**Issue by Kirky-J** [ND-iTC/Documents#205]
Section 1.2 para 8

“To reach a ‘fail’ verdict for the Assurance Component when these Evaluation Activities have been successfully completed would require a specific justification from the evaluator as to why the Evaluation Activities were not sufficient for that TOE.”

Consider removing this text.

**Comment by Kirky-J** [comment]
Offending text removed.

Fixed in editorial-SD-Fixes-v3_0

**Comment by kr15tyk** [comment]
Issues resolved with PR #209
