### ISSUE TITLE
Misc. SD terminology and glossary fixes

### ISSUE THREAD

**Issue by Kirky-J** [ND-iTC/Documents#206]
Section 1.4.1 Para 13

Removal of 'Key Chaining' from glossary.

Section 1.4.2

Consider adding the following terms to acronyms table: IKE, SSH, RBG, FQDN, CRL, OCSP, FFC.
Consider splitting EC and DHE into two separate entries.

Consider removing entry for SAR, as this is standard CC terminology. Alternatively, include entries for both SAR and SFR.

CN and DN have incorrect ‘meaning’.

SAN abbreviation explained as a Storage Area Network. SAN as a Storage Area Network is not used anywhere in the SD, while SAN as a Subject Alternative Name is used in multiple places.

**Comment by Kirky-J** [comment]
Key Chaining Removed. All other acronyms added and/or corrected in section 1.4.2.

Fixed in editorial-SD-Fixes-v3_0

**Comment by kr15tyk** [comment]
Issues resolved with PR #209
