### ISSUE TITLE
[cPP ENHANCEMENT] Add reference from FAU_GEN.1 to PKG_SSH_V1.0

### ISSUE THREAD

**Issue by dundiddat** [ND-iTC/Documents#229]
**Provide the location of the issue**
	6.3.1.1, FAU_GEN.1 Audit data generation (Refinement)

**What is the enhancement request for the cPP? Please describe.**
	FAU_GEN.1 Application Note 4 does not explain the requirement to include auditable events found in FP SSH v1.0 Table 1 and Table 2. 

**Describe the solution you'd like**
	Update to explicitly reference auditable events specified in the SSH functional package.

**Comment by dundiddat** [comment]
Related to issue #123

**Comment by KSinitski** [comment]
Agreed.

**Comment by a-kandiah** [comment]
I take it that the suggestions made in #123 should close this off?
