### ISSUE TITLE
[cPP ENHANCEMENT] Add auditable event for FPT_TST_EXT.1

### ISSUE THREAD

**Issue by dundiddat** [ND-iTC/Documents#230]
**Provide the location of the issue**
	6.3.1.1, FAU_GEN.1 Audit data generation (Refinement)

**What is the enhancement request for the cPP? Please describe.**
	FAU_GEN.1 Table 2 FPT_TST_EXT.1 list ‘none’ for auditable events. Please explain why requirement to audit failure of startup self-test is not mandated through FAU_GEN.1?
	To account for cases where such failure happens too early in the boot process to audit, consider introducing an alternative in claiming FPT_FLS.1 (i.e., requirement to fail securely).

**Describe the solution you'd like**
	For FPT_TST_EXT.1, consider replacing ‘none’ with ‘errors during boot process’.

**Comment by KSinitski** [comment]
The failure to respond to FIPS self-tests errors must be clarified as an explicit nonconformity of FPT_TST_EXT.1

**Comment by KSinitski** [comment]
Unfortunately it is necessary to state the obvious - it is not acceptable to ignore self-test failure.

Recommend adding: 

FPT_TST_EXT.1.2 The TSF shall respond to [selection: all errors, [assignment: list of failures detected by self-tests]] by [selection: enter a maintenance mode, reboot, [assignment: other methods to recover secure state]].

**Comment by KSinitski** [comment]
I agree with Ken's proposed approach (per email thread) to address this issue by further modifying FPT_TST_EXT.1.2 element and associated TSS section.

**Comment by kr15tyk** [comment]
Resolved in PR https://github.com/ND-iTC/Documents/pull/307
