### ISSUE TITLE
[cPP ENHANCEMENT] Add FPT_FLS.1 or add failure state description to FPT_TST_EXT.1

### ISSUE THREAD

**Issue by dundiddat** [ND-iTC/Documents#237]
**Provide the location of the issue**
	6.7.2.1, FPT_TST_EXT.1 TSF Testing (Extended)

**What is the enhancement request for the cPP? Please describe.**
	FPT_TST_EXT.1 specifies a TSF testing but does not specify how to handle failure of self-tests. Please consider creating additional requirement to describe what happens when tests fail. Alternatively, consider introducing FPT_FLS.1.

**Describe the solution you'd like**
	Suggested update:
	
The TSF shall run a suite of the following self-tests
	… to demonstrate the correct operation of the TSF: [assignment: list of self-tests run by the TSF] and if failure detected [assignment: describe resulting error state].

**Comment by KSinitski** [comment]
Please introduce a requirement to document what action occurs when self-test fail.

**Comment by KSinitski** [comment]
I agree with Ken's proposed approach (per email thread) to address this issue by introducing FPT_TST_EXT.1.2 element.

**Comment by kr15tyk** [comment]
Resolved in PR https://github.com/ND-iTC/Documents/pull/307
