### ISSUE TITLE
Seemingly incorrect test equivalency between FCS_TLSC_EXT.1.1 test 3 and FCS_TLSC_EXT.1.5

### ISSUE THREAD

**Issue by mclearn** [ND-iTC/Documents#268]
**Provide the location of the issue**
In FCS_TLSC_EXT.1.1 test 3

**What is the correction request for the cPP? Please describe.**
In FCS_TLSC_EXT.1.1 test 3, the test case says the following: "Perform this test only if support of TLS 1.2 is claimed (corresponding testing for TLS 1.3 is covered by the tests for FCS_TLSC_EXT.1.5)"

This appears to incorrectly imply that FCS_TLSC_EXT.1.5 test cases cover the same result, but for TLS 1.3.  That is incorrect since FCS_TLSC_EXT.1.5 has no negative testing and FCS_TLSC_EXT.1.1 test 3 is only a negative test case.

**Describe the solution you'd like**
Remove the following in FCS_TLSC_EXT.1.1 test 3: "(corresponding testing for TLS 1.3 is covered by the tests for FCS_TLSC_EXT.1.5)"

The same solution should be applied to FCS_DTLSC_EXT.1 as well.

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by kr15tyk** [comment]
TLSWG agreed to Greg's suggested change on today's call.
