### ISSUE TITLE
[cPP TYPO] Obsolete SFR reference in SD for FAU_STG_EXT.1

### ISSUE THREAD

**Issue by OlegAndrianov** [ND-iTC/Documents#288]
**Provide the location of the issue**
SD Section 2.1.3.3. Tests.	Test 6 

**Describe the typo that you've identified. Please be specific**

> Test 6 [Conditional]: In case manual export or ability to view locally is selected in FAU_STG_EXT.1.4/LocSpace, 

**Describe the solution you'd like**

> Test 6 [Conditional]: In case manual export or ability to view locally is selected in FAU_STG_EXT.1.6, 

**Additional context**
Old SFR name remained.

**Comment by kr15tyk** [comment]
@OlegAndrianov Thank you. This will be corrected in NDcPPv3.0e.
