### ISSUE TITLE
[cPP Comment 26] FCS_(D)TLSC_EXT.1.8, FCS_(D)TLSS_EXT.1.10

### ISSUE THREAD

**Issue by kr15tyk** [ND-iTC/Documents#301]
**Location:** NDcPP: FCS_(D)TLSC_EXT.1.8; C.2.2.6; B.3.3.1 / FCS_(D)TLSS_EXT.1.10; B.3.3.1

**Comment:** Consider use of out-of-band PSK in closed communities.

**Suggested Change:** Remove requirement regarding externally sourced PSK.
“The TSF shall not permit DTLS 1.3 connections using PSKs that do not use (EC)DHE to provide forward secrecy.” 
And explain in the Application Note:
“If DTLS 1.3 is supported, the TOE will not accept connections using PSK in Key Exchange mode (psk_ke), but may support PSK in DHE mode (psk_dhe). If DTLS 1.3 is not supported, or if the supported DTLS 1.3 implementation does not support PSK, this element is satisfied by default.”

**Comment by kenji-lightship** [comment]
I'm not fundamentally against PSK support; but we had decided not to support out of band PSKs so we did not need to consider the security implications, specify allowed uses, and complicate the SFRs and testing for NDcPPv3.0

**Comment by kenji-lightship** [comment]
I think this should be a future enhancement and not something we address in 3.0e

**Comment by kr15tyk** [comment]
On the TLSWG call today, we agreed that this introduces a lot more work than it would be worth since this is a very unique use case. This should be a future enhancement if there is a request in the future.
