### ISSUE TITLE
[cPP Comment 27] NDcPP: FCS_DTLSS_EXT.1.9;  B.3.3.1; C.2.2.2

### ISSUE THREAD

**Issue by kr15tyk** [ND-iTC/Documents#302]
**Location:** NDcPP: FCS_DTLSS_EXT.1.9;  B.3.3.1; C.2.2.2

**Comment:** This element only applies to TLS 1.3, so if you’re not claiming TLS 1.3, this SFR (and 1.10) is null and void.

**Suggested change:** Reconfigure SFR so no elements are selection-based.

**Comment by kenji-lightship** [comment]
I think we can leave this as-is. Since the Early data extension not supported in TLS 1.2, I think we can make an argument that it is prohibited in a TLS1.2 connection as well as a TLS1.3 connection.
