### ISSUE TITLE
[cPP Correction] ND iTC allowed-with list does not contain VPNGW v1.3

### ISSUE THREAD

**Issue by OlegAndrianov** [ND-iTC/Documents#319]
**Provide the location of the issue**
[ND iTC allowed-with list for Network Device cPP](https://github.com/ND-iTC/Documents/blob/main/NDcPP_allowed_with_list.adoc#nd-itc-allowed-with-list-for-network-device-cpp)

**What is the correction request for the cPP? Please describe.**
Add newly released Module for Virtual Private Network (VPN) Gateway, Version 1.3 to the list https://www.niap-ccevs.org/Profile/Info.cfm?PPID=481&id=481
"Notable changes include fixing issues with multifactor authentication and applying all applicable NIAP Technical Decisions." as per NIAP.
 

**Additional context**
none

**Comment by kr15tyk** [comment]
@OlegAndrianov The Develpment branch includes the VPN GW module v1.3 which will be merged into the Main branch in the coming weeks.

https://github.com/ND-iTC/Documents/blob/Development/NDcPP_allowed_with_list.adoc
