### ISSUE TITLE
[SD TYPO] curves/groups are mixed up in Test description

### ISSUE THREAD

**Issue by OlegAndrianov** [ND-iTC/Documents#320]
**Provide the location of the issue**
FCS_DTLSC_EXT.1.4 Test 3, Test 4
FCS_TLSC_EXT.1.4 Test 3, Test 4

**Describe the typo that you've identified. Please be specific**
SD now states:

> Test 3 [conditional]: If secp **groups** are selected, 
> Test 4 [conditional]: If ffdhe **curves** are selected,

**Describe the solution you'd like**
Test 3 shall mention secp curves and Test 4 shall mention ffdhe groups instead.

**Additional context**
Add any other context or screenshots about the change request here.

**Comment by kr15tyk** [comment]
Corrected in commit https://github.com/ND-iTC/Documents/commit/a9665b5f02ebadeab5f664833adead48e3a0b1b0
