### ISSUE TITLE
[SD Correction] Missing 'null' guidance EAs for FCS_DTLSC_EXT.1 elements

### ISSUE THREAD

**Issue by jfisherbah** [ND-iTC/Documents#359]
**Provide the location of the issue**
FCS_DTLSC_EXT.1.10 and 1.11

**What is the correction request for the cPP? Please describe.**
FCS_DTLSC_EXT.1.10 and 1.11 are missing guidance EAs (assuming they should just say “None” but it should still be listed)

**Describe the solution you'd like**
We would like subheadings for the elements added with "None." underneath them as is done for other SFRs so that it's clear to the reader that guidance EAs for these elements were not left out by accident.

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by kr15tyk** [comment]
DTLS and TLS SFRs will be removed from the NDcPP and we will be pointing out to the NIAP FP for TLS.
