### ISSUE TITLE
TLSWG: FCS_TLSS_EXT.1.2 typo

### ISSUE THREAD

**Issue by mclearn** [ND-iTC/Documents#58]
In the SD under FCS_TLSS_EXT.1.2 for the tests section:

Test 1: The evaluator shall attempt to establish a TLS/SSL connection using each of the TLS/SSL versions (i.e., TLS 1.3, TLS 1.2, TLS 1.1, TLS 1.0, .0, SSL 2.0). 

The version "SSL 3.0" has been truncated to just ".0".

**Comment by kr15tyk** [comment]
@mclearn typo was corrected.
