### ISSUE TITLE
NIAP Comment on FCS_RBG_EXT.1

### ISSUE THREAD

**Issue by plughy2** [ND-iTC/Documents#62]
The iTC received a request from NIAP to address ambiguity found in FCS_RBG_EXT.1.1.  

This issue is, FCS_RBG_EXT.1.1 has a selection operation for Hash_DRBG (any) and HMAC_DRBG (any).
Why is "any" listed and what does "any" actually mean? Turns out, "any" means SHA-1 or SHA-256 or SHA-384 or SHA-512.  It follows this should be a selection operation instead of "any".  Addressing the ambiguity will help NIAP in their effort to automate checking of Security Targets that was being led by Bob Clemons.

**Comment by dundiddat** [comment]
That proposed change seems fine, and is consistent with what's already in Application Note 16 (under FCS_RBG_EXT.1): 
"While any of the identified hash functions (SHA-1, SHA-256, SHA-384, SHA-512) are allowed for Hash_DRBG or HMAC_DRBG, only AES-based implementations for CTR_DRBG are allowed."

**Comment by kr15tyk** [comment]
Issue closed with PR https://github.com/ND-iTC/Documents/pull/75
