### ISSUE TITLE
Obsoleted RFC

### ISSUE THREAD

**Issue by plughy2** [ND-iTC/Documents#65]
The following ciphersuites should reference RFC 8422 as RFC 4492 has been obsoleted by the IETF

TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA as defined in RFC 4492
TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA as defined in RFC 4492
TLS_ECDHE_ECDSA_WITH_AES_128_CBC_SHA as defined in RFC 4492
TLS_ECDHE_ECDSA_WITH_AES_256_CBC_SHA as defined in RFC 4492

**Comment by kr15tyk** [comment]
Resolved in https://github.com/ND-iTC/Documents/pull/66

**Comment by kr15tyk** [comment]
Resolved in https://github.com/ND-iTC/Documents/pull/66
