### ISSUE TITLE
NDcPPv3.0 Roadmap item - RFCs / NIST SPs

### ISSUE THREAD

**Issue by kr15tyk** [ND-iTC/Documents#70]
**Provide the location of the issue**
Throughout cPP and SD

**What is the enhancement request for the cPP? Please describe.**
Check references to standards (mainly RFCs and NIST SPs) to verify that they are still up to date.

**Describe the solution you'd like**
The MiNT/Cisco is working this item. A PR will be opened after other PRs are closed to avoid merge conflicts.

**Describe alternatives you've considered**
NA

**Additional context**
NA

**Comment by trwolff** [comment]
The following requirements and application note in ND cPP 2.2e refer to ISO/IEC 18031:2011:

    FCS_RBG_EXT.1.1
    FCS_RBG_EXT.1.2
    Application Note 16

This ISO was released in 2011, prior to NIST SP 800-90Arev1 being published, and is most likely not in line with current DRBG thinking. For example, it may still contain allowance for the Dual_EC_DRBG, which NIST disallowed in 2014. This ISO is currently being reviewed, but there is no date for when a new version will be released. Analysis is needed by the MiNT to determine if this standard still applies or if a different standard should be used.

**Comment by kr15tyk** [comment]
Opened issue for NIAP's VPN GW module recommending changing references to RFC 5996 now that it is obsoleted by RFC 7296, https://github.com/commoncriteria/vpngw/issues/11.

**Comment by kr15tyk** [comment]
Closing issue with completion of https://github.com/ND-iTC/Documents/pull/82

**Comment by kr15tyk** [comment]
Closing issue with since https://github.com/ND-iTC/Documents/pull/82 is complete.
