### ISSUE TITLE
MINT CR1-2022: X509 for web servers without mutual auth

### ISSUE THREAD

**Issue by plughy2** [ND-iTC/Documents#76]
@ConanHoye and MINT,

**Below is the background on the X.509 requirements for non-mutual authenticating web servers issue originally received by the NIT:**

The requirement in the NDcPP currently appears to require vendors to claim FIA_X509_EXT.1 and FIA_X509_EXT.2 if the TOE claims TLS in any capacity – even when only claiming FCS_TLSS_EXT.1(a non-mutually authenticating web server):

1. PP, section B.4.1: “X.509 certificate-based authentication is required if IPsec or TLS communications are claimed for FPT_ITT, FTP_ITC.1 or FTP_TRP.”
2. PP, section B.4.1: “Although the functionality in FIA_X509_EXT.1/Rev and FIA_X509_EXT.2 is always required when using X.509 certificate-based authentication, the TOE only needs to be able to generate a Certification Request if the TOE needs to present an X.509 certificate to another endpoint via the TSF for authentication (i.e. if at least one of the following SFRs is included in the ST: FCS_DTLSC_EXT.2, FCS_DTLSS_EXT.1, FCS_DTLSS_EXT.2, FCS_IPSEC_EXT.1, FCS_SSHC_EXT.1.5 (applicable only if at least one of the x509v3-* ciphers is selected), FCS_SSHS_EXT.1.5 (applicable only if at least one of the x509v3-* ciphers is selected), FCS_TLSC_EXT.2, FCS_TLSS_EXT.1, FCS_TLSS_EXT.2).. Therefore FIA_X509_EXT.3 only needs to be added to the ST in this case.”
3. Application Note 113 in the PP also says the following about FIA_X509_EXT.2:  “The ST author must include FIA_X509_EXT.2 in all instances except when only SSH is selected within FTP_ITC.1 or FPT_ITT.1 and ssh-rsa, ecdsa-sha2-nistp256, ecdsa-sha2-nistp384, and/or ecdsa-sha2-nistp521 authentication is also selected.”
4. Finally, section C.2.2.9 in the PP also provides dependencies requiring FIA_X509_EXT.1 and .2 for FCS_(D)TLSS_EXT.1. 

There is equal language throughout the PP (primarily within FIA_X509_EXT.1/Rev application notes) that suggest that it is understood that non-mutual authenticating web servers do not require the SFR to be met. 

We believe that the language and structure in the NDcPP is unintentionally forcing this requirement since there is no reasonable case where a product that implements a web server conforming with FCS_TLSS_EXT.1 for remote management (and makes use of SSH for all other mandatory channels) should be required to maintain a trust store and validate its own leaf certificate or its own intermediate CAs for revocation purposes at load time.  Such operations would occur precisely once and provide no security value, all the while requiring vendors to spend time and resources building such a requirement into their products.  When a TOE is responsible for delivering a certificate to another endpoint, the responsibility, by definition, resides with the non-TOE endpoint to verify the TOE’s certificate.

**Suggested Resolution for MINT:**

**NDcPPv2.2e, Section B.4.1, Authentication using X.509 certificates, shall be modified as follows:**

**[old]** 
X.509 certificate-based authentication is required if IPsec or TLS communications are claimed for FPT_ITT, FTP_ITC.1 or FTP_TRP. These SFRs are also required if FPT_TUD_EXT.2 claimed. 
**[/old]** 

**[new]** 
Support for X.509 certificate-based authentication is required if IPsec, TLS or DTLS communications are claimed for FPT_ITT.1, FTP_ITC.1 or FTP_TRP.1/Admin. Claiming functionality in FIA_X509_EXT.1/Rev is mandatory when using certificate-based authentication as part of establishing secure channel with a remote endpoint where the TOE performs certificate validation.  These SFRs are also required if FPT_TUD_EXT.2 is claimed.
**[/new]** 

**NDcPPv2.2e, Section A.3.1.1, FIA_X509_EXT.1/ITT  Application Note 44 shall be modified as follows:**

**[old]** 
The chain validation is expected to terminate with a trust anchor. This means the validation can terminate with any trusted CA certificate designated as a trust anchor. This CA certificate must be loaded into the trust store ('certificate store', ' trusted CA Key Store' or similar) managed by the platform. If the TOE’s trust store supports loading of multiple hierarchical CA certificates or certificate chains, the TOE must clearly indicate all certificates it considers trust anchors.
**[/old]** 

**[new]** 
The certificate chain validation is expected to terminate with a trust anchor. This means the validation can terminate with any trusted CA certificate administratively designated as a trust anchor or default to terminate with a Root CA. If the TOE validates certificates presented by remote endpoints (i.e., external IT entities, remote administrators, or remote parts of the TOE), the CA certificates designated as trust anchors must be loaded into the trust store ('certificate store', ' trusted CA Key Store' or similar) managed by the platform. In such cases, the TOE’s trust store must support loading of multiple hierarchical CA certificates or certificate chains and must clearly indicate all certificates it considers trust anchors. If the TOE only presents its own certificate (e.g., a web server without mutual authentication), implementing the trust store is optional. 
**[/new]** 

**NDcPPv2.2e, Section 6.9.1.1, FTP_ITC.1 Application Note 39 shall be modified as follows:**

**[old]** 
Where public key certificates are used in support of an FTP_ITC.1 channel, FIA_X509_EXT.1/Rev is to be used (this requires checking certificate revocation), and not the iteration FIA_X509_EXT.1/ITT which is only for use in inter-component channels of a distributed TOE.
**[/old]** 

**[new]** 
Where X.509 certificates are used to authenticate remote end points in support of an FTP_ITC.1 channel, FIA_X509_EXT.1/Rev is to be used (this requires checking certificate revocation, implementing a trust store and supporting certificate chain length of three). 
**[/new]** 

**NDcPPv2.2e, Section 6.9.2.1, FTP_TRP.1/Admin Application Note 40 shall be appended as follows:**

**[new]** 
Where X.509 certificates are used to authenticate authorized Administrators, FIA_X509_EXT.1/Rev is to be used (this requires checking certificate revocation, implementing a trust store and supporting certificate chain length of three).
**[/new]**

**ND SD v2.2, Section 3.2.1.1 FIA_X509_EXT.1/ITT TSS shall be modified as follows:**

**[old]** 
The evaluator shall examine the TSS to ensure it describes where the check of validity of the certificates takes place, and that the TSS identifies any of the rules for extendedKeyUsage fields (in FIA_X509_EXT.1.1) that are not supported by the TOE (i.e. where the ST is therefore claiming that they are trivially satisfied). If selected, the TSS shall describe how certificate revocation checking is performed. It is not sufficient to verify the status of a X.509 certificate only when it's loaded onto the device.
**[/old]** 

**[new]** 
The evaluator shall examine the TSS to ensure it describes in what circumstances the check of validity of the certificates takes place (e.g., when the TOE is presented with a certificate during secure channel negotiation), and that the TSS identifies any of the rules for checking extendedKeyUsage fields. If selected, the TSS shall list all supported revocation checking methods, specify in what circumstances revocation checking is performed, and categorically describe what certificates are checked (e.g., all certificates up to a Root CA). The evaluator shall confirm the TSS describes trust store implementation or explicitly states that the trust store is not implemented. 
**[/new]**

**NDcPP v2.2e, FMT_SMF.1 ‘Specification of Management Functions’ shall be modified as follows:**

**[old]** 
FMT_SMF.1.1 The TSF shall be capable of performing the following management functions:
…
[selection:
…
o	Ability to manage the TOE's trust store and designate X509.v3 certificates as trust anchors; 
o	Ability to import X.509v3 certificates to the TOE's trust store; 
o	No other capabilities].

Application Note 24
…
The selection "Ability to import X.509v3 certificates to the TOE's trust store" must be included in the ST if the TOE supports loading of X.509 certificates to the TOE's trust store.
**[/old]** 

**[new]** 
FMT_SMF.1.1 The TSF shall be capable of performing the following management functions:
…
[selection:
…
o	Ability to manage the TOE's trust store and designate X509 certificates as trust anchors; 
o	Ability to generate Certificate Signing Request (CSR) and process CA response; 
o	No other capabilities].
Application Note 24
…
The selection "Ability to generate Certificate Signing Request (CSR) and process CA response" must be included in the ST if the TOE implements Certificate Request or Enrollment Request processes.
**[/new]** 

Please note item 4 in the list is being addressed in Issue #69

**Comment by kr15tyk** [comment]
Issue closed with merge of https://github.com/ND-iTC/Documents/pull/80
