### ISSUE TITLE
[cPP Correction]

### ISSUE THREAD

**Issue by Bill-yc** [ND-iTC/Documents#99]
**Provide the location of the issue**
Dependencies of FCS_COP.1 (in particular, FCS_COP.1/SigGen)
And the dependency table in Appendix E.1
 
**What is the correction request for the cPP? Please describe.**
According to CC part 2, the dependency of FCS_COP.1 is:

[**FDP_ITC.1** Import of user data without security
attributes, or
**FDP_ITC.2** Import of user data with security attributes,
or
FCS_CKM.1 Cryptographic key generation] FCS_CKM.4 Cryptographic key destruction

Not **FTP_ITC.1**, as stated in appendix E.1.
This is particularly a problem for the FCS_COP.1/SigGen for trust update, as most of the time the public key / certificate used to verify the firmware is imported externally rather than generated by the TOE. At this moment I do not think the cPP fulfills the correct dependency for FCS_COP.1/SigGen

**Describe the solution you'd like**
1. Update the table in appendix E.1 of the FCS_COP.1 to change the dependency from FTP_ITC.1 to FDP_ITC.1
2. Include FDP_ITC.1 and it’s dependencies (FDP_IFC.1/FDP_ACC.1/FMT_MSA.3) to correctly address the dependency of FCS_COP.1 in case the key in imported instead of generated by the TOE

**Describe alternatives you've considered**
Clearly describe the rationale why dependency FTP_ITC.1 does not need to be met even if the key is imported

**Comment by Kirky-J** [comment]
Issue is being investigated.
